"""Add column is_available in movies

Revision ID: 009273ca983c
Revises: c6b854dab25c
Create Date: 2025-10-19 22:28:47.200823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009273ca983c'
down_revision: Union[str, Sequence[str], None] = 'c6b854dab25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.alter_column('movies_rating', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('movies_rating_user_id_fkey'), 'movies_rating', type_='foreignkey')
    op.drop_constraint(op.f('movies_rating_movie_id_fkey'), 'movies_rating', type_='foreignkey')
    op.create_foreign_key(None, 'movies_rating', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movies_rating', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies_rating', type_='foreignkey')
    op.drop_constraint(None, 'movies_rating', type_='foreignkey')
    op.create_foreign_key(op.f('movies_rating_movie_id_fkey'), 'movies_rating', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('movies_rating_user_id_fkey'), 'movies_rating', 'users', ['user_id'], ['id'])
    op.alter_column('movies_rating', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('movies', 'is_available')
    # ### end Alembic commands ###
